# Generated by Django 4.2.16 on 2024-12-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_delete_favorite_favoritelist_user_and_more'),
        ('notebook', '0002_alter_notebook_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='favorite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='favorites.favoritecountry'),
        ),
    ]
