# Generated by Django 4.2.16 on 2024-12-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_notebook_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='favorite',
            new_name='favorite_country',
        ),
    ]
