# Generated by Django 4.2.16 on 2024-12-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0006_alter_favoritecountry_id'),
        ('notebook', '0004_rename_favorite_notebook_favorite_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='favorite_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='favorites.favoritecountry'),
        ),
    ]
