# Generated by Django 4.2.16 on 2024-11-20 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('date_encountered', models.DateField(default='2008-01-01')),
                ('description', models.TextField(default='Unknown', validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(150)])),
                ('captured', models.BooleanField(default=False)),
            ],
        ),
    ]
