# Generated by Django 4.2.16 on 2024-11-19 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('date_released', models.DateField(default='2015-01-1')),
                ('description', models.TextField(default='A standard vehicle', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(150)])),
                ('purchased', models.BooleanField(default=False)),
            ],
        ),
    ]
