# Generated by Django 4.2.16 on 2024-12-10 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_favoritecountry_favoritelist_remove_favorite_country_and_more'),
        ('countries', '0001_initial'),
        ('notebook', '0002_alter_notebook_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritecountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='countries.country'),
        ),
        migrations.AddField(
            model_name='favoritecountry',
            name='favorite_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_countries', to='favorites.favoritelist'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecountry',
            unique_together={('favorite_list', 'country')},
        ),
    ]
