# Generated by Django 4.2.16 on 2024-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_delete_favorite_favoritelist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecountry',
            name='id',
        ),
        migrations.AddField(
            model_name='favoritecountry',
            name='favorite_country_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
